### PR TITLE
Fixed snapping

### LINKED ISSUE #29: improved snap

### LINKED ISSUE #32: Listing organization fails in domain mode
When running this system in domain mode, list organizations endpoint fails with following error:

org.infinispan.commons.marshall.NotSerializableException: fi.otavanopisto.kuntaapi.server.settings.OrganizationSettingController

### PR DESCRIPTION
**Pull request by hkurhinen**
Fixes #29 Fixes #32

### CODE REVIEW

**Comment by sonarq** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. CRITICAL [OrganizationSettingController.java#L31](https://github.com/otavanopisto/kunta-api-server/blob/65cc59544dc7854155bb37319e1ab5cf76963723/src/main/java/fi/otavanopisto/kuntaapi/server/settings/OrganizationSettingController.java#L31): Make "logger" transient or serializable. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS1948)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 1]
```diff
@@ -578,7 +577,8 @@ public Response getOrganizationTileImageData(String organizationIdParam, String
 
   @Override
   public Response createOrganizationSetting(String organizationIdParam, OrganizationSetting setting) {
-    OrganizationId organizationId = toOrganizationId(organizationIdParam);
+    return createNotImplemented(NOT_IMPLEMENTED);
+    /*OrganizationId organizationId = toOrganizationId(organizationIdParam);
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 2]
```diff
@@ -1140,7 +1145,7 @@ private OffsetDateTime getDateTime(String timeString) {
 
 
   private fi.otavanopisto.kuntaapi.server.persistence.model.OrganizationSetting findOrganizationSetting(OrganizationId organizationId, String settingId) {
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR Remove this unused method parameter "organizationId". [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 3]
```diff
@@ -1140,7 +1145,7 @@ private OffsetDateTime getDateTime(String timeString) {
...
-    fi.otavanopisto.kuntaapi.server.persistence.model.OrganizationSetting organizationSetting = organizationSettingController.findOrganizationSetting(settingId);
+    /*fi.otavanopisto.kuntaapi.server.persistence.model.OrganizationSetting organizationSetting = organizationSettingController.findOrganizationSetting(settingId);
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 4]
```diff
@@ -648,7 +649,8 @@ public Response findOrganizationSetting(String organizationIdParam, String setti
   @Override
   @SuppressWarnings ("squid:MethodCyclomaticComplexity")
   public Response updateOrganizationSetting(String organizationIdParam, String settingId, OrganizationSetting setting) {
-    OrganizationId organizationId = toOrganizationId(organizationIdParam);
+    return createNotImplemented(NOT_IMPLEMENTED);
+    /*OrganizationId organizationId = toOrganizationId(organizationIdParam);
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 5]
```diff
@@ -674,11 +676,13 @@ public Response updateOrganizationSetting(String organizationIdParam, String set
...
         .entity(createOrganizationEntity(updatedSetting))
-        .build();
+        .build();*/
   }
 
   @Override
   public Response deleteOrganizationSetting(String organizationIdParam, String settingId) {
+    return createNotImplemented(NOT_IMPLEMENTED);
+    /*
     OrganizationId organizationId = toOrganizationId(organizationIdParam);
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 6]
```diff
@@ -76,8 +75,8 @@
   @Inject
   private Logger logger;
   
-  @Inject
-  private OrganizationSettingController organizationSettingController;
+  //@Inject
+  //private transient OrganizationSettingController organizationSettingController;
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java [hunk 7]
```diff
@@ -598,12 +598,13 @@ public Response createOrganizationSetting(String organizationIdParam, Organizati
...
         .entity(createOrganizationEntity(organizationSettingController.createOrganizationSetting(setting.getKey(), setting.getValue(), organizationId)))
-        .build();
+        .build();*/
   }
 
   @Override
   public Response listOrganizationSettings(String organizationIdParam, String key) {
-    OrganizationId organizationId = toOrganizationId(organizationIdParam);
+    return createNotImplemented(NOT_IMPLEMENTED);
+   /* OrganizationId organizationId = toOrganizationId(organizationIdParam);
```
Comment (sonarq) [inline src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

**Comment by sonarq** [comment]
SonarQube analysis reported 7 issues
* MAJOR 7 major

Watch the comments in this conversation to review them.

**Comment by sonarq** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [OrganizationsApiImpl.java#L84](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L84): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L589](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L589): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L615](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L615): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L661](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L661): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L694](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L694): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L1244](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L1244): Remove this unused method parameter "organizationId". [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS1172)
1. MAJOR [OrganizationsApiImpl.java#L1245](https://github.com/otavanopisto/kunta-api-server/blob/73b62c7152561430a4a69e3b28438bf44a7ec1cb/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L1245): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

**Comment by sonarq** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [OrganizationsApiImpl.java#L84](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L84): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L589](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L589): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L615](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L615): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L661](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L661): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L694](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L694): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. MAJOR [OrganizationsApiImpl.java#L1244](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L1244): Remove this unused method parameter "organizationId". [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS1172)
1. MAJOR [OrganizationsApiImpl.java#L1245](https://github.com/otavanopisto/kunta-api-server/blob/e3f507c25bed21904329a7f82f67dc7d8ce701a7/src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java#L1245): This block of commented-out lines of code should be removed. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
